# Copyright (c) 2005-2015 Ross Smith II (http://smithii.com). MIT Licensed.

/*
# todo add:
#http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz

64 bit versions

CurrPorts - View open TCP-IP connections (64bit)"   "http://www.nirsoft.net/utils/cports-x64.zip"   "cports.exe"    ""
NetPass - Reveal network passwords (64bit)" "http://www.nirsoft.net/utils/netpass-x64.zip"  "netpass.exe"   ""
SpecialFoldersView - View special folder locations (64bit)" "http://www.nirsoft.net/utils/specialfoldersview-x64.zip"   "specialfoldersview.exe"    ""
ProduKey - Reveal Office, Windows CD keys (64bit)"  "http://www.nirsoft.net/utils/produkey-x64.zip" "ProduKey.exe"  ""
RegScanner - RegEdit alternative (64bit XP+)"   "http://www.nirsoft.net/utils/regscanner-x64.zip"   "RegScanner.exe"    ""
FileTypesMan - 'File type' manager alternative (64bit XP+)" "http://www.nirsoft.net/utils/filetypesman-x64.zip" "filetypesman.exe"  ""
ShellExView - Shell extensions manager (64 bit)"    "http://www.nirsoft.net/utils/shexview-x64.zip" "shexview.exe"  ""
ShellMenuView - Manage context menu items (64bit XP+)"  "http://www.nirsoft.net/utils/shmnview-x64.zip" "shmnview.exe"  ""
SysExporter - Grab data from UI components (64bit)" "http://www.nirsoft.net/utils/sysexp-x64.zip"   "sysexp.exe"    ""
VoluMouse (Beta 3) - Control volume with mouse wheel (64bit)"   "http://www.nirsoft.net/utils/volumouse_beta-x64.zip"   "volumouse.exe" ""
VoluMouse - Control volume with mouse wheel (64bit)"    "http://www.nirsoft.net/utils/volumouse-x64.zip"    "volumouse.exe" ""
DriverView - View loaded device drivers (64bit XP+)"    "http://www.nirsoft.net/utils/driverview-x64.zip"   "DriverView.exe"    ""
RegDllView - View registered DLL,OCX,EXE's (64bit)" "http://www.nirsoft.net/utils/regdllview-x64.zip"   "RegDllView.exe"    ""
ProcessActivityView - View process access of files & folders (64bit XP+)"   "http://www.nirsoft.net/utils/processactivityview-x64.zip"  "processactivityview.exe"   ""
RegFromApp - Creates .reg file from application (64bit XP+)"    "http://www.nirsoft.net/utils/regfromapp-x64.zip"   "regfromapp.exe"    ""
DLL Export Viewer - View DLL exported functions (64bit)"    "http://www.nirsoft.net/utils/dllexp-x64.zip"   "dllexp.exe"    ""
HeapMemView - Dump heap memory (64bit XP+)" "http://www.nirsoft.net/utils/heapmemview-x64.zip"  ""
GDI View - View GDI handles (64bit XP+)"    "http://www.nirsoft.net/utils/gdiview-x64.zip"  "gdiview.exe"   ""
RunAsDate - Run program using specified date & time (64bit XP+)"    "http://www.nirsoft.net/utils/runasdate-x64.zip"    "RunAsDate.exe" ""
OutlookAddressBookView - View Outlook address books (XP+ 64bit)"	"		http://www.nirsoft.net/utils/outlookaddressbookview-x64.zip" "outlookaddressbookview" ""

BrowsingHistoryView - View browser history for IE, Firefox, Chrome, and Safari (64bit XP+)"  "http://www.nirsoft.net/utils/browsinghistoryview-x64.zip"   "browsinghistoryview.exe" ""
MultiMonitorTool - Work with multiple monitors (64bit XP+)"  "http://www.nirsoft.net/utils/multimonitortool-x64.zip"   "multimonitortool.exe" ""

TcpLogView - View TCP connections (64bit XP+)

missing on http://www.nirsoft.net/x64_download_package.html :

NetworkTrafficView
ProcessThreadsView
WebSiteSniffer
WebCookiesSniffer
WirelessKeyDump

1	 wirelesskeyview.zip	 256,706
2	 bluetoothview.zip	 141,571
3	 mailpv.zip	 88,630
4	 produkey.zip	 85,608
5	 webbrowserpassview.zip	 82,869
6	 bluescreenview.zip	 65,258
7	 videocacheview.zip	 59,921
8	 wnetwatcher.zip	 57,230
9	 iepv.zip	 53,699
10	 usbdeview.zip	 48,280

        1: Top Ten (Windows 32 bit)
        2: Top Ten (Windows 64 bit)
        3: All - Windows 64 bit - All versions
        4: All - Windows 32 bit - 8/7/Vista or newer
        5: All - Windows 32 bit - 2008/2003/XP
        6: All - Windows 32 bit - 2000/NT
        7: All - Windows 32 bit - NT
        8: All - Windows 32 bit - ME/98/95
        9: All - Windows 32 bit - 95
*/

!insertmacro DownloadGUI "1 2 3 4 5 6 7"        "BluetoothView - Monitor the Bluetooth activity around you (NT+)"   "http://www.nirsoft.net/utils/bluetoothview.zip"    "bluetoothview.exe" "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "1 2 3 4 5"            "BlueScreenView - View 'Blue Screen of Death' crash information (XP+)"  "http://www.nirsoft.net/utils/bluescreenview.zip"   "bluescreenview.exe" "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "1 2 3 4 5 6 7 8 9"    "IEPassView - View IE passwords"    "http://www.nirsoft.net/toolsdownload/iepv.zip" "iepv.exe"  "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "1 2 3 4 5 6 7 8 9"    "MailPassView - Reveal mail passwords"  "http://www.nirsoft.net/toolsdownload/mailpv.zip"   "mailpv.exe"    "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "1     4 5 6 7 8 9"    "ProduKey - Reveal Office, Windows CD keys (32bit)" "http://www.nirsoft.net/utils/produkey.zip" "ProduKey.exe"  "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "  2 3"                "ProduKey - Reveal Office, Windows CD keys (64bit)" "http://www.nirsoft.net/utils/produkey-x64.zip" "ProduKey.exe"  "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadCpy "1 2 3 4 5 6"          "USBDeview - Download usb.ids (USB VendorID-ProductID file)"    "http://www.linux-usb.org/usb.ids"  "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "1 2 3 4 5 6"          "USBDeview - View all USB devices (2000+)"  "http://www.nirsoft.net/utils/usbdeview.zip"    "usbdeview.exe" "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "1 2 3 4 5 6 7 8 9"    "VideoCacheView - View vidoes in browser cache" "http://www.nirsoft.net/utils/videocacheview.zip"   "videocacheview.exe"    "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "1 2 3 4 5 6"          "WebBrowserPassView - View password for 4 browsers (2000+)" "http://www.nirsoft.net/toolsdownload/webbrowserpassview.zip"   "webbrowserpassview.exe"    "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "1 2 1 2 3 4 5"        "WirelessKeyView - Reveal wireless network keys (XP+)"  "http://www.nirsoft.net/toolsdownload/wirelesskeyview.zip"  "wirelesskeyview.exe"   "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "1 2 3 4 5 6"          "WirelessNetworkWatcher - View connected computers & devices (2000+)"   "http://www.nirsoft.net/utils/wnetwatcher.zip"  "wnetwatcher.exe"   "" "http://www.nirsoft.net/utils/"

!insertmacro DownloadGUI "3 4 5 6 7 8 9"        "AccessPV - Reveal MS Access database passwords"    "http://www.nirsoft.net/utils/accesspv.zip" "accesspv.exe"  "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6 7 8 9"        "ACM - ActiveX compatibility manager"   "http://www.nirsoft.net/utils/acm.zip"  "acm.exe"   "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6 7 8 9"        "ActiveXHelper - Manage ActiveX components" "http://www.nirsoft.net/utils/axhelper.zip" "axhelper.exe"  "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6 7 8 9"        "AdapterWatch - Monitor your network adapter"   "http://www.nirsoft.net/utils/awatch.zip"   "awatch.exe"    "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6 7 8 9"        "AddrView - Extract URLs from HTML pages"   "http://www.nirsoft.net/utils/addrview.zip" "AddrView.exe"  "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6"              "AlternateStreamView - View NTFS alternate streams (2000+)" "http://nirsoft.net/utils/alternatestreamview.zip"  "AlternateStreamView.exe"   "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadCLI "3 4 5 6"              "AltStreamDump - Dump NTFS alternate streams (2000+)"   "http://www.nirsoft.net/utils/altstreamdump.zip" "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4"                  "AppCrashView - View application crash dumps (Vista+)"  "http://www.nirsoft.net/utils/appcrashview.zip" "appcrashview.exe" "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadCLI "3 4 5 6 7 8 9"        "AspNetUserPass - Dump ASPNet user passwords"   "http://www.nirsoft.net/utils/anup.zip" "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6 7 8 9"        "AsterIE - Reveal IE passwords" "http://www.nirsoft.net/utils/asterie.zip"  "asterie.exe"   "" "http://www.nirsoft.net/utils/"
#!insertmacro DownloadGUI "3 4 5 6 7 8 9"        "Asterisk Logger - Reveal asterisk passwords"   "http://www.nirsoft.net/utils/astlog.zip"   "astlog.exe"    "" "http://www.nirsoft.net/utils/"
#!insertmacro DownloadGUI "3 4 5 6 7 8 9"        "AsterWin - Reveal passwords behind asterisks"    "http://www.nirsoft.net/utils/asterwin120.zip"  "asterwin.exe"  "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadCLI "3 4 5 6 7 8 9"        "AtNow - Near-future command scheduler" "http://www.nirsoft.net/utils/atnow.zip"    "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6"              "BatteryInfoView - View laptop battery information (2000+)" "http://www.nirsoft.net/utils/batteryinfoview.zip"  "batteryinfoview.exe"   "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5"                "BluetoothLogView - Monitor and log the Bluetooth activity around you (XP+)"   "http://www.nirsoft.net/utils/bluetoothlogview.zip"    "bluetoothlogview.exe" "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadCLI "3 4 5"                "BluetoothViewCLI - Monitor the Bluetooth activity around you (XP+)" "http://www.nirsoft.net/utils/bluetoothcl.zip"  "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "  4 5 6"              "BrowsingHistoryView - View browser history for IE, Firefox, Chrome, and Safari (32bit 2000+)"  "http://www.nirsoft.net/utils/browsinghistoryview.zip"   "browsinghistoryview.exe" "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3"                    "BrowsingHistoryView - View browser history for IE, Firefox, Chrome, and Safari (64bit XP+)"  "http://www.nirsoft.net/utils/browsinghistoryview-x64.zip"   "browsinghistoryview.exe" "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6"              "BulkFileChanger - Updated file times (2000+)" "http://www.nirsoft.net/utils/bulkfilechanger.zip"   "bulkfilechanger.exe"   "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6"              "BulletsPassView - Review passwords (2000+)"    "http://www.nirsoft.net/toolsdownload/bulletspassview.zip"  "BulletsPassView.exe"   "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6 7 8 9"        "ChromeCacheView - View Chrome cache"   "http://www.nirsoft.net/utils/chromecacheview.zip"  "chromecacheview.exe"   "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6"              "ChromeCookiesView - View Chrome cookies (2000+)"   "http://www.nirsoft.net/utils/chromecookiesview.zip" "chromecookiesview.exe" "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6"              "ChromeHistoryView - View Chrome history (2000+)"   "http://www.nirsoft.net/utils/chromehistoryview.zip" "chromehistoryview.exe" "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6 7 8 9"        "ChromePass - Reveal Chrome passwords"  "http://www.nirsoft.net/toolsdownload/chromepass.zip"   "chromepass.exe"    "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6 7"            "CleanAfterMe - Auto clean files and registry entries (NT+)"    "http://www.nirsoft.net/utils/cleanafterme.zip" "cleanafterme.exe"  "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6"              "Clipboardic - Save clipboard activity to .clp files (2000+)"   "http://www.nirsoft.net/utils/clipboardic.zip"  "clipboardic.exe"   "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6 7 8 9"        "ConAdvPass - Content Advisor password remover" "http://www.nirsoft.net/utils/conadvpass.zip"   "conadvpass.exe"    "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6 7 8 9"        "CSVFileView - View or convert tab or comma separated value (CSV) files"    "http://www.nirsoft.net/utils/csvfileview.zip" "csvfileview.exe"    "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "  4 5 6 7 8 9"        "CurrPorts - View open TCP-IP connections (32bit)"  "http://www.nirsoft.net/utils/cports.zip"   "cports.exe"    "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3"                    "CurrPorts - View open TCP-IP connections (64bit)"  "http://www.nirsoft.net/utils/cports-x64.zip"   "cports.exe"    "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadCLI "3 4 5 6 7 8 9"        "CurrPorts - ~Download IpToCountry.csv (IP-to-country map)"  "http://smithii.com/files/IpToCountry.csv.zip"  "" "http://www.nirsoft.net/utils/"
# http://software77.net/geo-ip/?DL=2
!insertmacro DownloadGUI "3 4 5 6 7 8 9"        "CurrProcess - Process viewer for Windows" "http://www.nirsoft.net/utils/cprocess.zip" "CProcess.exe"  "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4"                  "CustomExplorerToolbar - Customize the toolbar of Windows Explorer (7+)"    "http://www.nirsoft.net/utils/customexplorertoolbar.zip"    "customexplorertoolbar.exe" "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6 7 8 9"        "CustomizeIE - View & manage IE toolbar buttons"    "http://www.nirsoft.net/utils/ctie.zip" "ctie.exe"  "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6"              "DeviceIOView - Watch data transfer between software or service & device driver (NT+)"  "http://www.nirsoft.net/utils/deviceioview.zip" "deviceioview.exe"  "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6"              "DevManView - View all installed devices (2000+)"   "http://www.nirsoft.net/utils/devmanview.zip"   "devmanview.exe"    "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6"              "Dialupass - Reveal dial-up passwords (2000+)"  "http://www.nirsoft.net/toolsdownload/dialupass.zip"    "dialupass.exe" "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "7 8"                  "Dialupass2 - Reveal dial-up passwords (98-NT)" "http://www.nirsoft.net/toolsdownload/dialupass2.zip"   "dialupass2.exe"    "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5"                "DiskCountersView - View hard disk counters (XP+)"  "http://www.nirsoft.net/utils/diskcountersview.zip" "diskcountersview.exe" "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6"              "DiskSmartView - View S.M.A.R.T hard disk information (2000+)"  "http://www.nirsoft.net/utils/disksmartview.zip" "disksmartview.exe" "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "  4 5 6 7 8 9"        "DLLExportViewer - View DLL exported functions (32bit)"   "http://www.nirsoft.net/utils/dllexp.zip"   "dllexp.exe"    "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3"                    "DLLExportViewer - View DLL exported functions (64bit)"   "http://www.nirsoft.net/utils/dllexp-x64.zip"   "dllexp.exe"    "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5"                "DNSDataView - GUI alternative to nslookup (XP+)"   "http://www.nirsoft.net/utils/dnsdataview.zip"  "dnsdataview.exe"   "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "  4 5 6"              "DNSQuerySniffer - View DNS queries sent by your system (32bit 2000+)"  "http://www.nirsoft.net/utils/dnsquerysniffer.zip"   "dnsquerysniffer.exe"    "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3"                    "DNSQuerySniffer - View DNS queries sent by your system (64bit XP+)"  "http://www.nirsoft.net/utils/dnsquerysniffer-x64.zip"   "dnsquerysniffer.exe"    "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5"                "DomainHostingView - View report of domain's DNS and WHOIS information (XP+)"   "http://www.nirsoft.net/utils/domainhostingview.zip"    "domainhostingview.exe" "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6 7 8 9"        "DotNetResourcesExtract - Extract resources from .NET applications" "http://www.nirsoft.net/utils/dotnetresourcesextract.zip"   "dotnetresourcesextract.exe"    "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6 7 8 9"        "DownTester - Test download speed"  "http://www.nirsoft.net/utils/downtester.zip"   "downtester.exe"    "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6"              "DriveLetterView - View & change drive letter assignments (2000+)"  "http://www.nirsoft.net/utils/driveletterview.zip" "driveletterview.exe" "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "  4 5 6 7"            "DriverView - View loaded device drivers (32bit NT+)"   "http://www.nirsoft.net/utils/driverview.zip"   "DriverView.exe"    "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3"                    "DriverView - View loaded device drivers (64bit XP+)"   "http://www.nirsoft.net/utils/driverview-x64.zip"   "DriverView.exe"    "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadCLI "3 4 5 6 7"            "DumpEDID - Dump extended display identification (NT+)" "http://www.nirsoft.net/utils/dumpedid.zip" "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6 7 8 9"        "Empv - Reveal MS-SQL server passwords" "http://www.nirsoft.net/utils/empv.zip" "empv.exe"  "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6"              "ESEDatabaseView - View .EDB databases (2000+)" "http://www.nirsoft.net/utils/esedatabaseview.zip"  "esedatabaseview.exe"   "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6 7 8 9"        "ExeInfo - View .EXE header information"    "http://www.nirsoft.net/utils/exeinfo.zip"  "exeinfo.exe"   "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6"			    "ExifDataView - List Exif data in JPEG images (2000+)"	"http://www.nirsoft.net/utils/exifdataview.zip"	"exifdataview.exe"	"" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "10   4 5 6"           "EventLogSourcesView - View event log sources (32bit 2000+)"  "http://www.nirsoft.net/utils/eventlogsourcesview.zip"   "eventlogsourcesview.exe"    "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "11 3"                 "EventLogSourcesView - View event log sources (64bit XP+)"  "http://www.nirsoft.net/utils/eventlogsourcesview-x64.zip"   "eventlogsourcesview.exe"    "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "10 11 3 4 5"          "ExecutedProgramsList - View previously executed programs (XP+)" "http://www.nirsoft.net/utils/executedprogramslist.zip"   "executedprogramslist.exe"	"" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6 7 8 9"        "ExploreStart - Restart Windows Explorer"   "http://www.nirsoft.net/utils/explorestart.zip" "explorestart.exe"  "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6 7 8 9"        "FastResolver - Resolve multiple hosts, IPs"    "http://www.nirsoft.net/utils/fastresolver.zip" "FastResolver.exe"  "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "10 11 3 4 5"          "FBCacheView - View Facebook images stored in your Web browser cache (XP+)" "http://www.nirsoft.net/utils/fbcacheview.zip"   "fbcacheview.exe"	"" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6 7 8 9"        "FavoritesView - View IE favorites, bookmarks"  "http://www.nirsoft.net/utils/faview.zip"   "faview.exe"    "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6 7 8 9"        "FileDateChanger - Change file's created-modified-accessed dates"   "http://www.nirsoft.net/utils/filedatech.zip"   "FileDate.exe"  "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "  4 5 6 7"            "FileTypesMan - 'File type' manager alternative (32bit NT+)"    "http://www.nirsoft.net/utils/filetypesman.zip" "filetypesman.exe"  "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3"                    "FileTypesMan - 'File type' manager alternative (64bit XP+)"    "http://www.nirsoft.net/utils/filetypesman-x64.zip" "filetypesman.exe"  "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "8"                    "FileTypesMan - 'File type' manager alternative (98-ME)"    "http://www.nirsoft.net/utils/filetypesman-98.zip"  "filetypesman.exe"  "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6"              "FirefoxDownloadsView - View Firefox downloads (2000+)" "http://www.nirsoft.net/utils/firefoxdownloadsview.zip" "firefoxdownloadsview.exe" "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "12 13 3 4 5"          "FirmwareTablesView - View firmware tables (XP+)" "http://www.nirsoft.net/utils/firmwaretablesview.zip"   "firmwaretablesview.exe"	"" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6"              "FlashCookiesView - View Flash cookies (2000+)" "http://www.nirsoft.net/utils/flashcookiesview.zip" "flashcookiesview.exe" "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6"              "FolderChangesView - Monitors folder or disk drive changes (2000+)" "http://www.nirsoft.net/utils/folderchangesview.zip"  "folderchangesview.exe"   "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6 7 8 9"        "FoldersReport - Folder usage report"   "http://www.nirsoft.net/utils/folrep.zip"   "folrep.exe"    "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "10   4 5 6"           "FolderTimeUpdate - Update modified time of folders to last time of files in it (32bit 2000+)"  "http://www.nirsoft.net/utils/foldertimeupdate.zip"   "foldertimeupdate.exe"    "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "11 3"                 "FolderTimeUpdate - Update modified time of folders to last time of files in it (64bit XP+)"  "http://www.nirsoft.net/utils/foldertimeupdate-x64.zip"   "foldertimeupdate.exe"    "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6 7 8 9"        "GACView - .NET assembly viewer alternative"    "http://www.nirsoft.net/dot_net_tools/gacview.zip"  "gacview.exe"   "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "  4 5 6 7"            "GDIView - View GDI handles (32bit NT+)"   "http://www.nirsoft.net/utils/gdiview.zip"  "gdiview.exe"   "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3"                    "GDIView - View GDI handles (64bit XP+)"   "http://www.nirsoft.net/utils/gdiview-x64.zip"  "gdiview.exe"   "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadCLI "3 4 5 6 7 8 9"        "GoogRank - Dump Google pagerank (CLI version)" "http://www.nirsoft.net/utils/grankcmd.zip" "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6 7 8 9"        "GoogRank - View Google pagerank (GUI version)" "http://www.nirsoft.net/utils/grank.zip"    "grank.exe" "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6 7"            "HashMyFiles - Calculate MD5, SHA1, CRC32 hashes (NT+)" "http://www.nirsoft.net/utils/hashmyfiles_u.zip"    "hashmyfiles.exe"   "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "8 9"                  "HashMyFiles - Calculate MD5, SHA1, CRC32 hashes (Win95-ME)"    "http://www.nirsoft.net/utils/hashmyfiles.zip"  "hashmyfiles.exe"   "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadCLI "  4 5 6 7"            "HeapMemView - Dump heap memory (32bit NT+)"    "http://www.nirsoft.net/utils/heapmemview.zip"  "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadCLI "3"                    "HeapMemView - Dump heap memory (64bit XP+)"    "http://www.nirsoft.net/utils/heapmemview-x64.zip"  "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6 7 8 9"        "HTMLAsText - Convert HTML to text" "http://www.nirsoft.net/utils/htmlastext.zip"   "HtmlAsText.exe"    "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6 7 8 9"        "HTMLDocEdit - Simple HTML designer; editor"    "http://www.nirsoft.net/utils/htmldocedit.zip"  "htmldocedit.exe"   "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6 7 8 9"        "IconsExtract - Extract icons from EXEs & DLLs" "http://www.nirsoft.net/utils/iconsext.zip" "iconsext.exe"  "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6 7 8 9"        "IdenSwitch - Switch identities in Outlook Express" "http://www.nirsoft.net/utils/idenswitch.zip"   "idenswitch.exe"    "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6 7 8 9"        "IECacheView - View IE cache"   "http://www.nirsoft.net/utils/iecacheview.zip"  "iecacheview.exe"   "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6 7 8 9"        "IECompo - View IE components"  "http://www.nirsoft.net/utils/iecompo.zip"  "IECompo.exe"   "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6 7 8 9"        "IECookiesView - View & manage IE Cookies"  "http://www.nirsoft.net/utils/iecv.zip" "iecv.exe"  "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6 7 8 9"        "IEDesignMode - Switch IE to design mode"   "http://www.nirsoft.net/utils/iedesignmode.zip" "IEDesignMode.exe"  "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6 7 8 9"        "IEHistoryView - View IE history"   "http://www.nirsoft.net/utils/iehv.zip" "iehv.exe"  "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "10 11 3 4 5"          "ImageCacheViewer - View images your Web browser cache (XP+)" "http://www.nirsoft.net/utils/imagecacheviewer.zip"  "imagecacheviewer.exe"   "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6 7 8 9"        "InjectedDLL - View automatically injected DLLs"    "http://www.nirsoft.net/utils/injecteddll.zip"  "injecteddll.exe"   "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6 7 8 9"        "InsideClipboard - View clipboard contents" "http://www.nirsoft.net/utils/insideclipboard.zip"  "insideclipboard.exe"   "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6 7"            "InstalledCodec - View installed codecs (NT+)"  "http://www.nirsoft.net/utils/installedcodec.zip"   "InstalledCodec.exe"    "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "10   4 5 6"           "InstalledDriversList  - View all currently installed device drivers (32bit 2000+)"  "http://www.nirsoft.net/utils/installeddriverslist.zip"   "installeddriverslist.exe"    "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "11 3"                 "InstalledDriversList  - View all currently installed device drivers (64bit XP+)"  "http://www.nirsoft.net/utils/installeddriverslist-x64.zip"   "installeddriverslist.exe"    "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6 7 8"          "IPInfoOffline - View IP Address Information Offline (Win98+)"  "http://www.nirsoft.net/utils/ipinfooffline.zip"    "ipinfooffline.exe" "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadCLI "3 4 5 6 7 8 9"        "IPInfoOffline - ~Download IpToCountry.csv (IP-to-country map)"  "http://smithii.com/files/IpToCountry.zip"  "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6 7 8 9"        "IPNetInfo - Retrieves IP address information"  "http://www.nirsoft.net/utils/ipnetinfo.zip"    "ipnetinfo.exe" "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6 7 8 9"        "JavaScript Animator Express - Create JavaScript animations"    "http://www.nirsoft.net/utils/jsae.zip" "jsae.exe"  "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6 7 8 9"        "JRView - View installed JDKs & JREs"   "http://www.nirsoft.net/utils/jrview.zip"   "jrview.exe"    "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "  4 5 6"              "LastActivityView - View user and system activity (2000+)"  "http://www.nirsoft.net/utils/lastactivityview.zip"   "lastactivityview.exe" "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6 7 8 9"        "LiveContactsView - View MSN Live contacts" "http://www.nirsoft.net/utils/livecontactsview.zip" "livecontactsview.exe"  "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadCLI "3 4 5 6 7"            "LSASecretsDump - Dump RSA & VPN passwords (NT+) (CLI version)" "http://www.nirsoft.net/toolsdownload/lsasecretsdump.zip"   "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6 7"            "LSASecretsView - View RSA & VPN passwords (NT+) (GUI version)" "http://www.nirsoft.net/toolsdownload/lsasecretsview.zip"   "lsasecretsview.exe"    "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadCpy "3 4 5 6 7 8 9"        "MACAddressView - Lookup MAC address company information (oui.txt)" "http://standards.ieee.org/regauth/oui/oui.txt" "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6 7 8"          "MACAddressView - Lookup MAC address company information (Win98+)"  "http://www.nirsoft.net/utils/macaddressview.zip"   "macaddressview.exe"    "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6 7 8 9"        "MessenPass - Reveal instant messenger passwords"   "http://www.nirsoft.net/toolsdownload/mspass.zip"   "mspass.exe"    "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6 7 8 9"        "MetarWeather - Decode METAR weather reports"   "http://www.nirsoft.net/utils/mweather.zip" "mweather.exe"  "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6 7 8 9"        "MIMEView - View MIME types"    "http://www.nirsoft.net/utils/mimeview.zip" "MIMEView.exe"  "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6 7 8 9"        "MMCompView - View codecs & ActiveX filters"    "http://www.nirsoft.net/utils/mmview.zip"   "mmview.exe"    "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6 7"            "MonitorInfoView - View monitor information (NT+)"  "http://www.nirsoft.net/utils/monitorinfoview.zip"  "monitorinfoview.exe"   "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6 7 8 9"        "MozillaCacheView - View Firefox caches"    "http://www.nirsoft.net/utils/mozillacacheview.zip" "mozillacacheview.exe"  "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6 7 8 9"        "MozillaCookiesView - View Firefox cookies" "http://www.nirsoft.net/utils/mzcv.zip" "mzcv.exe"  "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6 7 8 9"        "MozillaHistoryView - View Firefox history" "http://www.nirsoft.net/utils/mozillahistoryview.zip"   "mozillahistoryview.exe"    "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6 7"            "MUICacheView - MuiCache viewer, editor (NT+)"  "http://www.nirsoft.net/utils/muicacheview.zip" "muicacheview.exe"  "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "  4 5"                "MultiMonitorTool - Work with multiple monitors (32bit XP+)"  "http://www.nirsoft.net/utils/multimonitortool.zip"   "multimonitortool.exe" "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3"                    "MultiMonitorTool - Work with multiple monitors (64bit XP+)"  "http://www.nirsoft.net/utils/multimonitortool-x64.zip"   "multimonitortool.exe" "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6 7"            "MyEventViewer - Event log viewer (NT+)"    "http://www.nirsoft.net/utils/myeventviewer.zip"    "MyEventViewer.exe" "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6 7 8 9"        "MyLastSearch - View IE,Firefox,Mozilla searches"   "http://www.nirsoft.net/utils/mylastsearch.zip" "MyLastSearch.exe"  "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6 7 8 9"        "MyUninstaller - Add & remove program manager"  "http://www.nirsoft.net/utils/myuninst.zip" "myuninst.exe"  "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6"		        "NetBScanner - NetBIOS network scanner (2000+)"	"http://www.nirsoft.net/utils/netbscanner.zip"	"netbscanner.exe"	"" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6"              "NetConnectChoose - Choose default Internet connection (2000+)"    "http://www.nirsoft.net/utils/netconnectchoose.zip" "netconnectchoose.exe"  "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "  4 5 6 7 8 9"        "NetPass - Reveal network passwords (32bit)"    "http://www.nirsoft.net/toolsdownload/netpass.zip"  "netpass.exe"   "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3"                    "NetPass - Reveal network passwords (64bit)"    "http://www.nirsoft.net/toolsdownload/netpass-x64.zip"  "netpass.exe"   "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6 7"            "NetResView - View network computers & shares (NT+)"    "http://www.nirsoft.net/utils/netresview.zip"   "NetResView.exe"    "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6"              "NetRouteView - View network routes (2000+)"    "http://www.nirsoft.net/utils/netrouteview.zip" "netrouteview.exe"  "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6 7 8 9"        "NetscaPass - Reveal Netscape browser passwords"    "http://www.nirsoft.net/utils/netscapass.zip"   "Netscapass.exe"    "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "10 11 3 4 5 6"        "NetworkConnectLog - Logs network connections (2000+)" "http://www.nirsoft.net/utils/networkconnectlog.zip"  "networkconnectlog.exe"   "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6"              "NetworkInterfacesView - View network interfaces (2000+)"    "http://www.nirsoft.net/utils/networkinterfacesview.zip" "networkinterfacesview.exe"  "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "10   4 5 6"           "NetworkLatencyView - View TCP network latency (32bit 2000+)"  "http://www.nirsoft.net/utils/networklatencyview.zip"   "networklatencyview.exe"    "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "11 3"                 "NetworkLatencyView - View TCP network latency (64bit XP+)"  "http://www.nirsoft.net/utils/networklatencyview-x64.zip"   "networklatencyview.exe"    "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "  4 5 6"              "NetworkTrafficView - View TCP-IP network traffic (32bit 2000+)"    "http://www.nirsoft.net/utils/networktrafficview.zip"   "networktrafficview.exe"    "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3"                    "NetworkTrafficView - View TCP-IP network traffic (64bit XP+)"  "http://www.nirsoft.net/utils/networktrafficview-x64.zip"   "networktrafficview.exe"    "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6 7 8 9"        "NirCmd - Freeware command-line tool"   "http://www.nirsoft.net/utils/nircmd.zip"   "nircmd.exe"    "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6 7 8 9"        "NirExt - Add 3 useful context menu extensions" "http://www.nirsoft.net/utils/nirext.zip"   "nirext.exe"    "" "http://www.nirsoft.net/utils/"
#!insertmacro DownloadGUI "3 4 5 6 7 8 9"       "NirLauncher"   "http://download.nirsoft.net/nirsoft_package_beta_102a.zip" "NirLauncher.exe" "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6"              "NK2Edit - Edit Outlook auto-complete addresses (2000+)" "http://www.nirsoft.net/utils/nk2edit.zip" "nk2edit.exe"   "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6 7"            "NK2View - Reveal Outlook autocomplete emails (NT+)"    "http://www.nirsoft.net/utils/nk2view_u.zip"    "nk2view.exe"   "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "8 9"                  "NK2View - Reveal Outlook autocomplete emails (Win95-ME)"   "http://www.nirsoft.net/utils/nk2view.zip"  "nk2view.exe"   "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4"			        "NTFSLinksView - View symbolic links and junction points (Vista+)"	"http://www.nirsoft.net/utils/ntfslinksview.zip"	"ntfslinksview.exe"	"" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6 7 8 9"        "OfficeIns - Microsoft Office add-ins manager"  "http://www.nirsoft.net/utils/officeins.zip"    "OfficeIns.exe" "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6 7"            "OpenedFilesView - View all opened & locked files (NT+)"    "http://www.nirsoft.net/utils/ofview.zip"   "OpenedFilesView.exe"   "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "10  4 5 6"            "OpenSaveFilesView - View previously opened files using standard open-save Windows dialog box (32bit 2000+)" "http://www.nirsoft.net/utils/opensavefilesview.zip"   "opensavefilesview.exe"    "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "11 3"                 "OpenSaveFilesView - View previously opened files using standard open-save Windows dialog box (64bit XP+)"   "http://www.nirsoft.net/utils/opensavefilesview-x64.zip"   "opensavefilesview.exe"    "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6"              "OpenWithView - Disable,Enable items in the 'Open With' dialog-box of Windows (NT+)"    "http://www.nirsoft.net/utils/openwithview.zip" "openwithview.exe"  "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6 7"            "OperaCacheView - View Opera Cache (NT+)"   "http://www.nirsoft.net/utils/operacacheview.zip"   "OperaCacheView.exe"    "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "8 9"                  "OperaCacheView - View Opera Cache (Win95-ME)"  "http://www.nirsoft.net/utils/operacacheview-98.zip"    "OperaCacheView.exe"    "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6"              "OperaPassView - View Opera passwords (2000+)"  "http://www.nirsoft.net/toolsdownload/operapassview.zip" "operapassview.exe" "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6"        		"OutlookAddressBookView - View Outlook address books (2000+ 32bit)"	"http://www.nirsoft.net/utils/outlookaddressbookview.zip"	"outlookaddressbookview.exe"	"" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3"        			"OutlookAddressBookView - View Outlook address books (XP+ 64bit)"	"http://www.nirsoft.net/utils/outlookaddressbookview-x64.zip" "outlookaddressbookview.exe" "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6"              "OutlookAttachView - View Outlook attachments (2000+)"  "http://www.nirsoft.net/utils/outlookattachview.zip"    "outlookattachview.exe" "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6"              "OutlookStatView - View Outlook mailbox statistics (2000+)" "http://www.nirsoft.net/utils/outlookstatview.zip"  "outlookstatview.exe"   "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6 7 8 9"        "PasswordFox - Reveal Firefox passwords"    "http://www.nirsoft.net/toolsdownload/passwordfox.zip"  "passwordfox.exe"   "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6"              "PasswordSecurityScan - scan application passwords (2000+)"    "http://www.nirsoft.net/utils/passwordscan.zip"  "passwordscan.exe"   "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6 7 8 9"        "PcAnyPass - Reveal pcANYWHERE passwords"   "http://www.nirsoft.net/utils/pcanypass.zip"    "PCAnyPass.exe" "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6 7 8 9"        "PcAnyScan - View pcANYWHERE hosts" "http://www.nirsoft.net/utils/pcanyscan.zip"    "pcanyscan.exe" "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6 7"            "PingInfoView - Ping multiple hosts,IP addressses (NT+)"    "http://www.nirsoft.net/utils/pinginfoview.zip" "pinginfoview.exe"  "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "  4 5 6 7"            "ProcessActivityView - View process access of files & folders (32bit NT+)"  "http://www.nirsoft.net/utils/processactivityview.zip"  "processactivityview.exe"   "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3"                    "ProcessActivityView - View process access of files & folders (64bit XP+)"  "http://www.nirsoft.net/utils/processactivityview-x64.zip"  "processactivityview.exe"   "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "  4 5 6"              "ProcessThreadsView - List threads of a selected process (32bit 2000+)" "http://www.nirsoft.net/utils/processthreadsview.zip"   "processthreadsview.exe"    "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3"                    "ProcessThreadsView - List threads of a selected process (64bit XP+)"   "http://www.nirsoft.net/utils/processthreadsview-x64.zip"   "processthreadsview.exe"    "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6 7 8 9"        "ProtectedStoragePassView - Reveal Protected Storage passwords" "http://www.nirsoft.net/toolsdownload/pspv.zip" "pspv.exe"  "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6 7 8 9"        "PSTPassword - Reveal Outlook PST passwords"    "http://www.nirsoft.net/toolsdownload/pstpassword.zip"  "PstPassword.exe"   "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "10 11 3 4 5 6"        "QuickSetDNS - Easily change DNS servers (2000+)" "http://www.nirsoft.net/utils/quicksetdns.zip"  "quicksetdns.exe"   "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6 7"            "RecentFilesView - View recently used files (NT+)"  "http://www.nirsoft.net/utils/recentfilesview_u.zip"    "recentfilesview.exe"   "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "8 9"                  "RecentFilesView - View recently used files (Win95-ME)" "http://www.nirsoft.net/utils/recentfilesview.zip"  "recentfilesview.exe"   "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "  4 5 6 7 8 9"        "RegDllView - View registered DLL,OCX,EXE's (32bit)"    "http://www.nirsoft.net/utils/regdllview.zip"   "RegDllView.exe"    "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3"                    "RegDllView - View registered DLL,OCX,EXE's (64bit)"    "http://www.nirsoft.net/utils/regdllview-x64.zip"   "RegDllView.exe"    "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6"              "RegFileExport - Dump Windows registry to .reg file (2000+)"    "http://www.nirsoft.net/utils/regfileexport.zip" "regfileexport.exe" "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "  4 5 6 7"            "RegFromApp - Creates .reg file from application (32bit NT+)"   "http://www.nirsoft.net/utils/regfromapp.zip"   "regfromapp.exe"    "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3"                    "RegFromApp - Creates .reg file from application (64bit XP+)"   "http://www.nirsoft.net/utils/regfromapp-x64.zip"   "regfromapp.exe"    "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "  4 5 6 7"            "RegScanner - RegEdit alternative (32bit NT+)"  "http://www.nirsoft.net/utils/regscanner.zip"   "RegScanner.exe"    "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3"                    "RegScanner - RegEdit alternative (64bit XP+)"  "http://www.nirsoft.net/utils/regscanner-x64.zip"   "RegScanner.exe"    "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "8"                    "RegScanner - RegEdit alternative (Win98)"  "http://www.nirsoft.net/utils/regscanner-98.zip"    "RegScanner.exe"    "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6"              "Remote Desktop PassView - Reveal RDP passwords (2000+)"    "http://www.nirsoft.net/toolsdownload/rdpv.zip" "rdpv.exe"  "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6 7"            "ResourcesExtract - Extract resources from DLL,OCX,EXE files (NT+)" "http://www.nirsoft.net/utils/resourcesextract.zip" "resourcesextract.exe"  "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "8 9"                  "ResourcesExtract - Extract resources from DLL,OCX,EXE files (Win95-ME)"    "http://www.nirsoft.net/utils/resourcesextract-98.zip"  "resourcesextract.exe"  "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6"              "RouterPassView - View details in router backup files (2000+)" "http://www.nirsoft.net/toolsdownload/routerpassview.zip"    "routerpassview.exe"    "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5"                "RTMPDumpHelper - Download RTMP video/audio streams (XP+)"  "http://www.nirsoft.net/utils/rtmpdumphelper.zip"   "rtmpdumphelper.exe" "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "  4 5 6 7"            "RunAsDate - Run program using specified date & time (32bit NT+)"   "http://www.nirsoft.net/utils/runasdate.zip"    "RunAsDate.exe" "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3"                    "RunAsDate - Run program using specified date & time (64bit XP+)"   "http://www.nirsoft.net/utils/runasdate-x64.zip"    "RunAsDate.exe" "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6"              "SearchFilterView - View installed search filters (2000+)"  "http://www.nirsoft.net/utils/searchfilterview.zip" "searchfilterview.exe" "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6"              "SearchMyFiles - Improved file search method (2000+)"   "http://www.nirsoft.net/utils/searchmyfiles.zip"    "searchmyfiles.exe" "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6 7 8 9"        "SeqDownload - Web image downloader"    "http://www.nirsoft.net/utils/seqdownload.zip"  "SeqDownload.exe"   "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6 7"            "ServiWin - Windows service manager alternative (NT+)"  "http://www.nirsoft.net/utils/serviwin.zip" "serviwin.exe"  "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6 7 8 9"        "ShellBagsView - View saved folders settings"   "http://www.nirsoft.net/utils/shellbagsview.zip"    "shellbagsview.exe" "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "  4 5 6 7 8 9"        "ShellExView - Shell extensions manager (32bit)"    "http://www.nirsoft.net/utils/shexview.zip" "shexview.exe"  "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3"                    "ShellExView - Shell extensions manager (64bit)"   "http://www.nirsoft.net/utils/shexview-x64.zip" "shexview.exe"  "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6"              "ShellMenuNew - View 'New' menu items (2000+)"  "http://www.nirsoft.net/utils/shellmenunew.zip" "shellmenunew.exe" "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "  4 5 6 7"            "ShellMenuView - Manage context menu items (32bit NT+)" "http://www.nirsoft.net/utils/shmnview.zip" "shmnview.exe"  "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3"                    "ShellMenuView - Manage context menu items (64bit XP+)" "http://www.nirsoft.net/utils/shmnview-x64.zip" "shmnview.exe"  "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6 7 8 9"        "ShortcutsMan - Shortcuts manager for Windows"  "http://www.nirsoft.net/utils/shman.zip"    "shman.exe" "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6 7"            "SiteShoter - Save web page screenshots (NT+)"  "http://nirsoft.net/utils/siteshoter.zip"   "siteshoter.exe"    "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "10 11 3 4 5 6"        "SkypeContactsView - View Skype contacts (2000+)" "http://www.nirsoft.net/utils/skypecontactsview.zip"  "skypecontactsview.exe"   "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6"              "SkypeLogView - View Skype logs (2000+)"    "http://www.nirsoft.net/utils/skypelogview.zip" "skypelogview.exe"  "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6 7 8 9"        "SmartSniff - Packet sniffer"   "http://www.nirsoft.net/utils/smsniff.zip"  "smsniff.exe"   "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadCLI "3 4 5 6 7 8 9"        "SmartSniff - ~Download IpToCountry.csv (IP-to-country map)" "http://smithii.com/files/IpToCountry.zip"  "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "10   4 5"             "SimpleProgramDebugger - View major debugging events of attached program (32bit XP+)"  "http://www.nirsoft.net/utils/simpleprogramdebugger.zip"   "simpleprogramdebugger.exe"    "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "11 3"                 "SimpleProgramDebugger - View major debugging events of attached program (64bit XP+)"  "http://www.nirsoft.net/utils/simpleprogramdebugger-x64.zip"   "simpleprogramdebugger.exe"    "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6 7 8 9"        "SniffPass - Capture POP3,IMAP,SMTP,FTP,HTTP passwords" "http://www.nirsoft.net/toolsdownload/sniffpass.zip"    "SniffPass.exe" "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6 7 8 9"        "SNRemove - Removes reference to strong name signatures from .NET exes/dlls"    "http://www.nirsoft.net/dot_net_tools/snremove.zip" "snremove.exe"  "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6 7"            "SocketSniff - Watch WinSock activity of selected processes (NT+)"  "http://www.nirsoft.net/utils/socketsniff.zip"  "socketsniff.exe"   "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "10   4"               "SoundVolumeView - View sound volume levels by application (32bit Vista+)"  "http://www.nirsoft.net/utils/soundvolumeview.zip"   "soundvolumeview.exe"    "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "11 3"                 "SoundVolumeView - View sound volume levels by application (64bit Vista+)"  "http://www.nirsoft.net/utils/soundvolumeview-x64.zip"   "soundvolumeview.exe"    "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "  4 5 6 7"            "SpecialFoldersView - View special folder locations (32bit NT+)"    "http://www.nirsoft.net/utils/specialfoldersview.zip"   "specialfoldersview.exe"    "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3"                    "SpecialFoldersView - View special folder locations (64bit XP+)"    "http://www.nirsoft.net/utils/specialfoldersview-x64.zip"   "specialfoldersview.exe"    "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "8 9"                  "SpecialFoldersView - View special folder locations (Win95-ME)" "http://www.nirsoft.net/utils/specialfoldersview-98.zip"    "specialfoldersview.exe"    "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6"              "StartBlueScreen - Crash Windows by initiating a Blue Screen of Death (2000+)"  "http://www.nirsoft.net/utils/startbluescreen.zip"  "startbluescreen.exe"   "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "7 8 9"                "StartupRun - Windows startup manager (Win95-NT)"   "http://www.nirsoft.net/utils/strun.zip"    "strun.exe" "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "  4 5 6 7 8 9"        "SysExporter - Grab data from UI components (32bit)"    "http://www.nirsoft.net/utils/sysexp.zip"   "sysexp.exe"    "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3"                    "SysExporter - Grab data from UI components (64bit)"    "http://www.nirsoft.net/utils/sysexp-x64.zip"   "sysexp.exe"    "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6"              "TableTextCompare - View difference between 2 tab or comma-delimited (CSV) files (2000+)"   "http://www.nirsoft.net/utils/tabletextcompare.zip" "tabletextcompare.exe"  "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "10  4 5 6"            "TcpLogView - View TCP connections (32bit 2000+)" "http://www.nirsoft.net/utils/tcplogview.zip"   "tcplogview.exe"    "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "11 3"                 "TcpLogView - View TCP connections (64bit XP+)"   "http://www.nirsoft.net/utils/tcplogview-x64.zip"   "tcplogview.exe"    "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6 7 8 9"        "TagsReport - View HTML tag statistics" "http://www.nirsoft.net/utils/tagsrep.zip"  "TagsRep.exe"   "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6 7 8 9"        "TurnFlash - Enable or disable Flash in IE (GUI version)"   "http://www.nirsoft.net/utils/tflash210.zip"    "tflash.exe"    "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadCLI "3 4 5 6 7 8 9"        "TurnFlashCLI - Enable or disable Flash in IE (CLI version)"   "http://www.nirsoft.net/utils/tflash.zip"   "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6"              "TurnedOnTimesView - View when computer was power cycled (2000+)"    "http://www.nirsoft.net/utils/turnedontimesview.zip" "turnedontimesview.exe"  "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6 7"            "URLProtocolView - View installed URL protocols (NT+)"  "http://www.nirsoft.net/utils/urlprotocolview_u.zip"    "URLProtocolView.exe"   "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "8 9"                  "URLProtocolView - View installed URL protocols (Win95-ME)" "http://www.nirsoft.net/utils/urlprotocolview_u.zip"    "URLProtocolView.exe"   "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6"              "URLStringGrabber - Grab all URLs in IE window (2000+)" "http://www.nirsoft.net/utils/urlstringgrabber.zip" "urlstringgrabber.exe" "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6"              "USBLogView - View USB device log (2000+)"  "http://www.nirsoft.net/utils/usblogview.zip" "usblogview.exe" "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6 7 8 9"        "UserAssistView - View UserAssist registry entries" "http://nirsoft.net/utils/userassistview.zip"   "userassistview.exe"    "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6"              "UserProfilesView - View user profiles (2000+)" "http://www.nirsoft.net/utils/userprofilesview.zip" "userprofilesview.exe"  "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6 7 8 9"        "VNCPassView - Reveal VNC passwords"    "http://www.nirsoft.net/toolsdownload/vncpassview.zip"  "vncpassview.exe"   "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "  4 5 6 7 8 9"        "VoluMouse (Beta 3) - Control volume with mouse wheel (32bit)"  "http://www.nirsoft.net/utils/volumouse_beta.zip"   "volumouse.exe" "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3"                    "VoluMouse (Beta 3) - Control volume with mouse wheel (64bit)"  "http://www.nirsoft.net/utils/volumouse_beta-x64.zip"   "volumouse.exe" "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "  4 5 6 7 8 9"        "VoluMouse - Control volume with mouse wheel (32bit)"   "http://www.nirsoft.net/utils/volumouse.zip"    "volumouse.exe" "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3"                    "VoluMouse - Control volume with mouse wheel (64bit)"   "http://www.nirsoft.net/utils/volumouse-x64.zip"    "volumouse.exe" "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6"              "WakeMeOnLan - Turn on remote PCs using Wake-on-LAN (WOL) packets (2000+)"  "http://www.nirsoft.net/utils/wakemeonlan.zip"  "wakemeonlan.exe"   "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6"              "WebBrowserPassView - View password for 4 browsers (2000+)" "http://www.nirsoft.net/toolsdownload/webbrowserpassview.zip"   "webbrowserpassview.exe"    "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6"              "WebBrowserPassView - View password for 4 browsers (2000+)" "http://www.nirsoft.net/toolsdownload/webbrowserpassview.zip"   "webbrowserpassview.exe"    "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "10 11 3 4 5"          "WebCacheImageInfo - View EXIF information of .jpgs in your web browser caches (XP+)" "http://www.nirsoft.net/utils/webcacheimageinfo.zip"   "webcacheimageinfo.exe"	"" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6"              "WebCamImageSave - Capture web camera images every x seconds (2000+)" "http://www.nirsoft.net/utils/webcamimagesave.zip"    "webcamimagesave.exe"   "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "  4 5 6"              "WebCookiesSniffer - Capture web site cookies sent to browser (32bit 2000+)"    "http://www.nirsoft.net/utils/webcookiessniffer.zip"    "webcookiessniffer.exe" "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3"                    "WebCookiesSniffer - Capture web site cookies sent to browser (64bit XP+)"  "http://www.nirsoft.net/utils/webcookiessniffer-x64.zip"    "webcookiessniffer.exe" "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "  4 5 6"              "WebSiteSniffer - Save files downloaded by your browser (32bit 2000+)"  "http://www.nirsoft.net/utils/websitesniffer.zip"   "websitesniffer.exe"    "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3"                    "WebSiteSniffer - Save files downloaded by your browser (64bit XP+)"    "http://www.nirsoft.net/utils/websitesniffer-x64.zip"   "websitesniffer.exe"    "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6 7"            "WebVideoCap - Capture Flash video and RTSP streams (NT+)"  "http://www.nirsoft.net/utils/webvideocap.zip"  "webvideocap.exe"   "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6"              "WhatInStartup - Manage application run at startup (2000+)" "http://www.nirsoft.net/utils/whatinstartup.zip"    "whatinstartup.exe" "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6"              "WhatIsHang - View info for hung 32-bit applications (2000+)" "http://www.nirsoft.net/utils/whatishang.zip" "whatishang.exe"    "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "10   4 5 6"           "WhoIsConnectedSniffer - View network packets (32bit 2000+)"  "http://www.nirsoft.net/utils/whoisconnectedsniffer.zip"   "whoisconnectedsniffer.exe"    "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "11 3 "                "WhoIsConnectedSniffer - View network packets (64bit XP+)"  "http://www.nirsoft.net/utils/whoisconnectedsniffer-x64.zip"   "whoisconnectedsniffer.exe"    "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6 7 8 9"        "WhoisThisDomain - View WHOIS domain information (GUI version)" "http://www.nirsoft.net/utils/whoistd.zip"  "whoistd.exe"   "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadCLI "3 4 5 6 7 8 9"        "WhoisThisDomainCLI - Dump WHOIS domain information (CLI version)" "http://www.nirsoft.net/utils/whoiscl.zip"  "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadCLI "3 4 5 6 7 8 9"        "WhosIP - Get IP address from command line" "http://www.nirsoft.net/utils/whosip.zip"   "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "10   4"               "WifiChannelMonitor - View wireless access points and connected clients (32bit Vista+)"  "http://www.nirsoft.net/utils/wifichannelmonitor.zip"   "wifichannelmonitor.exe"    "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "11 3"                 "WifiChannelMonitor - View wireless access points and connected clients (64bit Vista+)"  "http://www.nirsoft.net/utils/wifichannelmonitor-x64.zip"   "wifichannelmonitor.exe"    "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "  4"                  "WifiInfoView - View extensive wireless network information (Vista+)"  "http://www.nirsoft.net/utils/wifiinfoview.zip"   "wifiinfoview.exe" "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "8 9"                  "Win9xPassView - Reveal Windows 95 & 98 passwords (Win95-ME)"   "http://www.nirsoft.net/utils/win9xpv.zip"  "win9xpv.exe"   "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6"              "WinCrashReport - View alternative crash report (2000+)"    "http://www.nirsoft.net/utils/wincrashreport.zip"   "wincrashreport.exe"    "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6 7 8 9"        "WinExplorer - View system's windows hierarchy" "http://www.nirsoft.net/utils/winexp.zip"   "winexp.exe"    "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6"              "WinFontsView - View installed fonts (2000+)"   "http://www.nirsoft.net/utils/winfontsview.zip" "winfontsview.exe"  "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6 7 8 9"        "WinLister - View opened windows"   "http://www.nirsoft.net/utils/winlister.zip"    "winlister.exe" "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "10 11 3 4"            "WinLogOnView - View Logon/Logoff events (Vista+)"  "http://www.nirsoft.net/utils/winlogonview.zip" "winlogonview.exe" "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6 7 8 9"        "WinMessControl - Enable & disable 'Windows Messenger'" "http://www.nirsoft.net/utils/wmc.zip"  "wmc.exe"   "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5"                "WinPrefetchView - View Windows pre-fetch (.pf) files (XP+)"    "http://www.nirsoft.net/utils/winprefetchview.zip" "winprefetchview.exe" "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "  4 5 6"              "WinsockServicesView - View Winsock service providers (2000+)"  "http://www.nirsoft.net/utils/winsockservicesview.zip"   "winsockservicesview.exe" "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6 7 8 9"        "WinUpdatesList - View installed service packs & hotfixes"  "http://www.nirsoft.net/utils/wul.zip"  "wul.exe"   "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "10 11 3 4"            "WirelessConnectionInfo - View information and statistics of wireless connection (Vista+)"  "http://www.nirsoft.net/utils/wirelessconnectioninfo.zip" "wirelessconnectioninfo.exe" "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadCLI "  4 5 6"              "WirelessKeyDump - Dump wireless keys (32bit 2000+)"    "http://www.nirsoft.net/utils/wirelesskeydump.zip" "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadCLI "3"                    "WirelessKeyDump - Dump wireless keys (64bit XP+)"  "http://www.nirsoft.net/utils/wirelesskeydump-x64.zip" "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadCLI "3 4 5"                "WirelessNetConsole - Dump wireless network information (XP+) " "http://www.nirsoft.net/utils/wirelessnetconsole.zip"   "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5"                "WirelessNetView - Monitor wireless networks on your area (XP+)"    "http://www.nirsoft.net/utils/wirelessnetview.zip"  "wirelessnetview.exe"   "" "http://www.nirsoft.net/utils/"
!insertmacro DownloadGUI "3 4 5 6 7 8 9"        "ZipInstaller - Install applications from .ZIP file"    "http://www.nirsoft.net/utils/zipinst.zip"  "zipinst.exe"   "" "http://www.nirsoft.net/utils/"

#src !insertmacro DownloadGUI "3 4 5 6 7 8 9"   "winexpsrc - WinExplorer"   "http://www.nirsoft.net/utils/winexpsrc.zip"    "winexp.exe"    ""
